/* English interface for the common feeding chart engine. */
window.petMealEnglish = {
  "ホーム画面のアプリで使う": "Use the Home Screen app",
  "この画面で参加しても、ホーム画面のアプリが共有になっているかは、アプリを開いて確認してね。": "Joining here does not automatically connect an app you have already added. Open your Home Screen app to check.",
  "下のボタンで招待リンクをコピー": "Copy the invitation link below",
  "招待リンクをコピー": "Copy invitation link",
  "コピーする招待リンク": "Invitation link to copy",
  "ホーム画面に戻って、犬／猫のアプリを開く": "Go to your Home Screen and open the dog or cat app",
  "表の下の「招待リンクで参加」を押す": "Tap “Join with a link” below the chart",
  "リンクを貼り付けて「この共有表に参加する」を押してね。": "Paste the link, then tap “Join this chart”.",
  "初回の設定だよ。参加後は、いつものアイコンから使えるよ。": "You only need to set this up once. After joining, use your usual Home Screen icon.",
  "閉じる": "Close",
  "コピーしたよ。次はホーム画面に戻って、アプリを開こう。": "Link copied. Go to your Home Screen and open the app.",
  "コピーできなかったので、下のリンクを長押ししてコピーしてね。": "Could not copy automatically. Touch and hold the link below, then choose Copy.",
  "引き継ぎの準備ができませんでした。ホーム画面のアプリで招待リンクを貼り付けてね。": "Could not prepare the handoff. Paste the invitation link in your Home Screen app instead.",
  "共有したままホーム画面に追加": "Add your shared chart to the Home Screen",
  "この共有表を、新しく追加するアプリへ引き継ぐ準備ができたよ。": "Your shared chart is ready to carry over to a newly added Home Screen app.",
  "この画面の共有ボタン（四角から上向き矢印）を押す": "Tap the browser’s Share button (a square with an upward arrow)",
  "見つからないときは、ブラウザのメニューを開いてね。": "If you cannot find it, open the browser menu.",
  "「ホーム画面に追加」を選ぶ": "Choose “Add to Home Screen”",
  "「Webアプリとして開く」が出たらオンのまま追加してね。": "If “Open as Web App” appears, leave it on and tap Add.",
  "追加したアイコンから開く": "Open the newly added icon",
  "ネットにつながった状態で「家族と共有中」と表示されるか確認してね。": "Connect to the internet and check that it says “Sharing with family”.",
  "今日中に追加してね。すでにあるアイコンは自動では切り替わりません。引き継がれなければ招待リンクを一度貼り付けて参加できます。": "Add it within 24 hours. Existing icons will not connect automatically. If the handoff does not work, paste the invitation link in the app to join.",
  "追加済みのアプリで使う手順": "Instructions for an existing Home Screen app",
  "これからホーム画面に追加する": "Add a new Home Screen app",
  "すでにアイコンを追加している": "I already have a Home Screen icon",
  "接続しています…": "Connecting…",
  "端末に保存済み・共有待ち": "Saved on this device · waiting to sync",
  "家族と共有中": "Sharing with family",
  "この端末だけに保存": "Saved on this device only",
  "保存できませんでした。端末の空き容量やブラウザの設定を確認してね。": "Could not save. Check your device storage and browser settings.",
  "家族と共有しているチェックを全部消しますか？": "Clear all checks on the shared family chart?",
  "今週のチェックを全部消しますか？": "Clear all checks for this week?",
  "同じマスの変更が重なったため、先に共有された記録を残しました": "Changes overlapped in the same cell. The first synced change was kept.",
  "端末に保存済み・接続できたら共有します": "Saved on this device · will sync when connected",
  "共有に接続できません。端末の記録を表示中": "Cannot connect to sharing. Showing the saved chart.",
  "共有を始めるときはインターネット接続が必要だよ。": "An internet connection is needed to start or join sharing.",
  "共有に接続できませんでした。通信状態とFirebaseのルールを確認してね。": "Could not connect to sharing. Check your internet connection and try again. If it continues, contact the app owner.",
  "今のチェックを家族と共有しますか？ 招待リンクを渡した人が確認・変更できるようになります。": "Share your current checks with family? Anyone you give the invitation link to can view and change this chart.",
  "招待リンクをコピーしたよ。家族に送ってね。": "Invitation link copied. Send it to your family.",
  "この招待リンクをコピーしてね": "Copy this invitation link",
  "共有処理が終わってから、もう一度押してね。": "Please wait for syncing to finish, then try again.",
  "まだ共有していない操作があります。接続して共有が終わってから切り替えてね。": "Some changes have not synced yet. Connect to the internet and wait for them to sync before leaving.",
  "この端末の共有をやめて、今のチェックを端末だけに保存しますか？ 家族側の共有は続きます。": "Stop sharing on this device and keep a local copy of the current checks? Your family’s shared chart will continue.",
  "端末に保存できませんでした。": "Could not save on this device.",
  "先に、今の共有待ちの操作を送信してね。": "Please sync your pending changes first.",
  "招待リンクで参加": "Join with a link",
  "家族から届いたリンクをコピーして、この欄に貼り付けてね。": "Copy the invitation link from your family and paste it here.",
  "招待リンク": "Invitation link",
  "ここを長押しして「ペースト」": "Touch and hold here, then choose Paste",
  "コピーしたリンクを貼り付ける": "Paste copied link",
  "この共有表に参加する": "Join this chart",
  "参加すると、家族と同じ表が表示されます。犬と猫の招待リンクは別々だよ。": "Joining opens your family’s shared chart. Dog and cat charts have separate invitation links.",
  "キャンセル": "Cancel",
  "貼り付けたよ。「この共有表に参加する」を押してね。": "Link pasted. Tap “Join this chart”.",
  "入力欄を長押しして「ペースト」を選んでね。": "Touch and hold the input field, then choose Paste.",
  "この表の招待リンクを貼ってね。犬と猫は別々だよ。": "Paste an invitation link for this chart. Dog and cat charts are separate.",
  "家族の共有表への招待": "You’re invited to a family chart",
  "どこで使うか選んでね。": "Choose how you want to use it.",
  "参加してホーム画面に追加する": "Join and add to Home Screen",
  "初めて使う方はこちら。参加してから追加します。": "New here? Join first, then add the app.",
  "追加済みのホーム画面のアプリで使う": "Use an existing Home Screen app",
  "すでに犬／猫のアイコンを追加している方はこちら。": "Choose this if you already have a dog or cat icon.",
  "この画面で使う": "Use it in this browser",
  "追加せず、この画面で使うこともできます。": "You can use the chart here without adding an app.",
  "あとで参加する": "Join later",
  "共有の引き継ぎ待ち・ネットにつながると参加します": "Waiting to join · will connect when you are online",
  "新しい版に更新": "Update app",
  "<h2 id=\"guide-title\">ホーム画面のアプリで使う</h2><p>この画面で参加しても、ホーム画面のアプリが共有になっているかは、アプリを開いて確認してね。</p><ol><li><strong>下のボタンで招待リンクをコピー</strong><button class=\"primary\" data-copy>招待リンクをコピー</button><p role=\"status\" data-copy-status></p><textarea aria-label=\"コピーする招待リンク\" data-link hidden readonly></textarea></li><li><strong>ホーム画面に戻って、犬／猫のアプリを開く</strong></li><li><strong>表の下の「招待リンクで参加」を押す</strong><br>リンクを貼り付けて「この共有表に参加する」を押してね。</li></ol><p class=\"guide-note\">初回の設定だよ。参加後は、いつものアイコンから使えるよ。</p><button data-close>閉じる</button>": "<h2 id=\"guide-title\">Use the Home Screen app</h2><p>Joining here does not automatically connect an app you have already added. Open your Home Screen app to check.</p><ol><li><strong>Copy the invitation link below</strong><button class=\"primary\" data-copy>Copy invitation link</button><p role=\"status\" data-copy-status></p><textarea aria-label=\"Invitation link to copy\" data-link hidden readonly></textarea></li><li><strong>Go to your Home Screen and open the dog or cat app</strong></li><li><strong>Tap “Join with a link” below the chart</strong><br>Paste the link, then tap “Join this chart”.</li></ol><p class=\"guide-note\">You only need to set this up once. After joining, use your usual Home Screen icon.</p><button data-close>Close</button>",
  "<h2 id=\"guide-title\">共有したままホーム画面に追加</h2><p>この共有表を、新しく追加するアプリへ引き継ぐ準備ができたよ。</p><ol><li><strong>この画面の共有ボタン（四角から上向き矢印）を押す</strong><br>見つからないときは、ブラウザのメニューを開いてね。</li><li><strong>「ホーム画面に追加」を選ぶ</strong><br>「Webアプリとして開く」が出たらオンのまま追加してね。</li><li><strong>追加したアイコンから開く</strong><br>ネットにつながった状態で「家族と共有中」と表示されるか確認してね。</li></ol><p class=\"guide-note\">今日中に追加してね。すでにあるアイコンは自動では切り替わりません。引き継がれなければ招待リンクを一度貼り付けて参加できます。</p><button data-manual>追加済みのアプリで使う手順</button><button data-close>閉じる</button>": "<h2 id=\"guide-title\">Add your shared chart to the Home Screen</h2><p>Your shared chart is ready to carry over to a newly added Home Screen app.</p><ol><li><strong>Tap the browser’s Share button (a square with an upward arrow)</strong><br>If you cannot find it, open the browser menu.</li><li><strong>Choose “Add to Home Screen”</strong><br>If “Open as Web App” appears, leave it on and tap Add.</li><li><strong>Open the newly added icon</strong><br>Connect to the internet and check that it says “Sharing with family”.</li></ol><p class=\"guide-note\">Add it within 24 hours. Existing icons will not connect automatically. If the handoff does not work, paste the invitation link in the app to join.</p><button data-manual>Instructions for an existing Home Screen app</button><button data-close>Close</button>",
  "<h2 id=\"guide-title\">ホーム画面のアプリで使う</h2><button class=\"primary\" data-install>これからホーム画面に追加する</button><button data-existing>すでにアイコンを追加している</button><button data-close>閉じる</button>": "<h2 id=\"guide-title\">Use the Home Screen app</h2><button class=\"primary\" data-install>Add a new Home Screen app</button><button data-existing>I already have a Home Screen icon</button><button data-close>Close</button>",
  "<h2 id=\"guide-title\">招待リンクで参加</h2><p>家族から届いたリンクをコピーして、この欄に貼り付けてね。</p><label for=\"join-link\">招待リンク</label><textarea id=\"join-link\" placeholder=\"ここを長押しして「ペースト」\" autocapitalize=\"off\" autocomplete=\"off\" spellcheck=\"false\"></textarea><button data-paste>コピーしたリンクを貼り付ける</button><p role=\"status\" data-join-status></p><button class=\"primary\" data-join>この共有表に参加する</button><p class=\"guide-note\">参加すると、家族と同じ表が表示されます。犬と猫の招待リンクは別々だよ。</p><button data-close>キャンセル</button>": "<h2 id=\"guide-title\">Join with a link</h2><p>Copy the invitation link from your family and paste it here.</p><label for=\"join-link\">Invitation link</label><textarea id=\"join-link\" placeholder=\"Touch and hold here, then choose Paste\" autocapitalize=\"off\" autocomplete=\"off\" spellcheck=\"false\"></textarea><button data-paste>Paste copied link</button><p role=\"status\" data-join-status></p><button class=\"primary\" data-join>Join this chart</button><p class=\"guide-note\">Joining opens your family’s shared chart. Dog and cat charts have separate invitation links.</p><button data-close>Cancel</button>",
  "<h2 id=\"guide-title\">家族の共有表への招待</h2><p>どこで使うか選んでね。</p><button class=\"primary\" data-install>参加してホーム画面に追加する</button><p class=\"guide-note\">初めて使う方はこちら。参加してから追加します。</p><button data-home>追加済みのホーム画面のアプリで使う</button><p class=\"guide-note\">すでに犬／猫のアイコンを追加している方はこちら。</p><button data-browser>この画面で使う</button><p class=\"guide-note\">追加せず、この画面で使うこともできます。</p><button data-close>あとで参加する</button>": "<h2 id=\"guide-title\">You’re invited to a family chart</h2><p>Choose how you want to use it.</p><button class=\"primary\" data-install>Join and add to Home Screen</button><p class=\"guide-note\">New here? Join first, then add the app.</p><button data-home>Use an existing Home Screen app</button><p class=\"guide-note\">Choose this if you already have a dog or cat icon.</p><button data-browser>Use it in this browser</button><p class=\"guide-note\">You can use the chart here without adding an app.</p><button data-close>Join later</button>"
};
